[[plugins]]
repository = 'The-NERD-Commenter'

[[plugins]]
repository = 'AutoClose'

[[plugins]]
repository = 't9md/vim-quickhl'

[[plugins]]
repository = 'endwise.vim'

[[plugins]]
repository = 'ruby-matchit'

[[plugins]]
repository = 'vim-ruby/vim-ruby'

[[plugins]]
repository = 'tpope/vim-rails'

[[plugins]]
repository = 'tpope/vim-surround'

[[plugins]]
repository = 'bling/vim-airline'

[[plugins]]
repository = 'Shougo/neocomplete.vim'

[[plugins]]
repository = 'Shougo/neosnippet'

[[plugins]]
repository = 'Shougo/neosnippet-snippets'

[[plugins]]
repository = 'Shougo/unite.vim'

[[plugins]]
repository = 'Shougo/neomru.vim'

[[plugins]]
repository = 'Shougo/vimfiler'

[[plugins]]
repository = 'Lokaltog/vim-easymotion'

[[plugins]]
repository = 'mattn/emmet-vim'

[[plugins]]
repository = 'thinca/vim-quickrun'

[[plugins]]
repository = 'monochromegane/unite-yaml'

[[plugins]]
repository = 'h1mesuke/vim-alignta'

[[plugins]]
repository = 'scrooloose/syntastic'

[[plugins]]
repository = 'osyo-manga/unite-quickfix'

[[plugins]]
repository = 'tomtom/tcomment_vim'

[[plugins]]
repository = 'kana/vim-textobj-user'

[[plugins]]
repository = 'osyo-manga/vim-textobj-multiblock'

[[plugins]]
repository = 'thoughtbot/vim-rspec'

[[plugins]]
repository = 'tpope/vim-dispatch'

[[plugins]]
repository = 'edsono/vim-matchit'

[[plugins]]
repository = 'fatih/vim-go'

[[plugins]]
repository = 'glidenote/memolist.vim'

[[plugins]]
repository = 'tomlion/vim-solidity'

[[plugins]]
repository = 'Shougo/vimproc.vim'

  [plugins.build]
    mac = 'make -f make_mac.mak'
    unix = 'make -f make_unix.mak'
